In [1]:
import quante as qt

In [2]:
L = 4
basis = qt.generate.basis.spin_basis(L, jmblock=(2, 2))

basis.print_dims(L)
# J 可取的值，可取 L/2, L2/2-1, ... 0，m 可取的值为 5, 4, 3, 2, 1, 0, -1, -2, -3, -4, -5
# dim 表示子空间的维数，num 表示子空间重复的次数

   J  |   num  |   dim   
-----------------------
  2.0 |   5    |  1
  1.0 |   3    |  3
  0.0 |   1    |  2
-----------------------
note: \sum num * dim = 2^L


In [3]:
ham = qt.generate.operas.heisenberg_operator(L)
mat = ham.to_matrix(basis)
print(mat.shape)  # 可以看到维数就是 1
mat[0,0]

(1, 1)


0.75

In [4]:
basis_ = qt.generate.basis.spin_basis(L)
mat_ = ham.to_matrix(basis_)
qt.linalg.eigvalsh(mat_).reshape(4,-1)
# 可以看到 0.75 确实重复的 5 次

array([[-1.6160254 , -0.95710678, -0.95710678, -0.95710678],
       [-0.25      , -0.25      , -0.25      ,  0.1160254 ],
       [ 0.45710678,  0.45710678,  0.45710678,  0.75      ],
       [ 0.75      ,  0.75      ,  0.75      ,  0.75      ]])

In [5]:
basis = qt.generate.basis.spin_basis(L, jmblock=(1, 1))
mat = ham.to_matrix(basis)
qt.linalg.eigvalsh(mat)
# 对比可以看到 这三个数每个都重复了三次

array([-0.95710678, -0.25      ,  0.45710678])

In [6]:
vec = basis.to_full_space(1)  # 第二个基矢，任何一个基矢都满足
# 这个向量是 J^2 的本征态

op = qt.generate.operas
op_Jx = op.sum(op.x(i) for i in range(L))
op_Jy = op.sum(op.y(i) for i in range(L))
op_Jz = op.sum(op.z(i) for i in range(L))
op_J2 = op_Jx**2 + op_Jy**2 + op_Jz**2

basis_ = qt.generate.basis.spin_basis(L)
mat_J2 = op_J2.to_matrix(basis_)

import numpy as np
np.real_if_close(mat_J2 @ vec - 1*(1+1)*vec)  # 这个向量是 J^2 的本征态

array([ 0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [7]:
basis_ = qt.generate.basis.spin_basis(L)
mat_Jz = op_Jz.to_matrix(basis_)

import numpy as np
np.real_if_close(mat_Jz @ vec - 1*vec)  # 这个向量是 Jz 的本征态

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])