## 算符代数的一些工具

目前主要是费米子的算符代数，后续会添加玻色子算符代数的内容。

In [1]:
import quante as qt
op = qt.generate.operas

builder = op.FermionBuilder()
builder += '-'*6 + '+'*6, list(range(1, 7))+list(range(1, 7)), 1.
ham = builder.build()
ham

FermionOper at 0x1a4e0033890, 
|   -     -     -     -     -     -     +     +     +     +     +     +       coef. |
|-----------------------------------------------------------------------------------|
|   1     2     3     4     5     6     1     2     3     4     5     6       1.000 |

In [2]:
ham.normal_ordering()

FermionOper at 0x1a4e33569c0, 
|   I       coef. |   +     -       coef. |   +     +     -     -       coef. |
|-----------------|-----------------------|-----------------------------------|
|   0      -1.000 |   1     1       1.000 |   1     2     1     2       1.000 |
|                 |   2     2       1.000 |   1     3     1     3       1.000 |
|                 |   3     3       1.000 |   2     3     2     3       1.000 |
|                 |   4     4       1.000 |   1     4     1     4       1.000 |
|                 |   5     5       1.000 |   2     4     2     4       1.000 |
|                 |   6     6       1.000 |   3     4     3     4       1.000 |
|                                         |   1     5     1     5       1.000 |
|                                         |   2     5     2     5       1.000 |
|                                         |   3     5     3     5       1.000 |
|                                         |   4     5     4     5       1.000 |
|        

## JW transformation

# 

In [ ]:
# JW transformation  spin -> fermion
import quante as qt

op = qt.generate.operas
builder = op.SpinBuilder()
L = 10
J, γ = 1, 0.0
for i in range(L-1):
    builder += "+-", [i+1, i], (J+γ)/2
    builder += "+-", [i, i+1], (J-γ)/2
ham = builder.build()

ham.jw_transfer()

FermionOper at 0x1a4df2b5850, 
|   +     -       coef. |
|-----------------------|
|   1     0      -0.500 |
|   0     1      -0.500 |
|   2     1      -0.500 |
|   1     2      -0.500 |
|   3     2      -0.500 |
|   2     3      -0.500 |
|   4     3      -0.500 |
|   3     4      -0.500 |
|   5     4      -0.500 |
|   4     5      -0.500 |
|   6     5      -0.500 |
|   5     6      -0.500 |
|   7     6      -0.500 |
|   6     7      -0.500 |
|   8     7      -0.500 |
|   7     8      -0.500 |
|   9     8      -0.500 |
|   8     9      -0.500 |

In [5]:
# JW transformation  fermion -> spin

import quante as qt

op = qt.generate.operas
builder = op.FermionBuilder()
L = 10
J, γ = 1, 0.0
for i in range(L-1):
    builder += "+-", [i+1, i], (J+γ)/2
    builder += "+-", [i, i+1], (J-γ)/2
ham = builder.build()

ham.jw_transfer()

SpinOper at 0x1a4df28bd10, 
|   m     p       coef. |   p     m       coef. |
|-----------------------|-----------------------|
|   0     1      -0.500 |   0     1      -0.500 |
|   1     2      -0.500 |   1     2      -0.500 |
|   2     3      -0.500 |   2     3      -0.500 |
|   3     4      -0.500 |   3     4      -0.500 |
|   4     5      -0.500 |   4     5      -0.500 |
|   5     6      -0.500 |   5     6      -0.500 |
|   6     7      -0.500 |   6     7      -0.500 |
|   7     8      -0.500 |   7     8      -0.500 |
|   8     9      -0.500 |   8     9      -0.500 |

In [8]:
# 验证正确性：
import quante as qt
import numpy as np

op = qt.generate.operas

L = 5
basis = qt.generate.basis.spin_basis(L=L)
ham = qt.generate.operas.heisenberg_operator(L=L).expandxy(pauli=True)
mat1 = ham.to_matrix(basis)
ham = ham.jw_transfer()  # spin -> fermion
ham = ham.jw_transfer()  # fermion -> spin
mat2 = ham.to_matrix(basis)
print(np.linalg.norm(mat1 - mat2))

0.0


In [10]:
# automata - fermion

# 验证正确性：
import quante as qt
import numpy as np

op = qt.generate.operas

L = 5
basis = qt.generate.basis.spin_basis(L=L)
ham = qt.generate.operas.heisenberg_operator(L=L).expandxy(pauli=True)
mat1 = ham.to_matrix(basis)
ham = ham.jw_transfer()  # spin -> fermion
ham = ham.jw_transfer()  # fermion -> spin
mpo = ham.to_mpo()
mat2 = mpo.to_matrix().numpy()
print(np.linalg.norm(mat1 - mat2))
print(mpo)

0.0
MPO;  torch.float64;  norm: 1.960e+01;  maxbonddim: 5;  device: cpu;
physdim:    2|    2|    2|    2|    2| 
         ----O-----O-----O-----O-----O----
physdim:    2|    2|    2|    2|    2| 
bonddim:  1     5     5     5     5     1
site:        0     1     2     3     4  


## Spinfull Femion

In [17]:
import quante as qt
op = qt.generate.operas.fermion

ham = op.SpinfulFermionOper.Fermi_Hubbard_operator(L=5)
print(ham)


SpinfulFermionOper (SpinUp | SpinDown) at 0x1a4e8d11970, 
|   +     -   |   coef. |   -     +   |   coef. | | +     -       coef. |
|-----------------------|-----------------------|-----------------------|
|   0     1      -1.000 |   0     1       1.000 |   0     1      -1.000 |
|   1     2      -1.000 |   1     2       1.000 |   1     2      -1.000 |
|   2     3      -1.000 |   2     3       1.000 |   2     3      -1.000 |
|   3     4      -1.000 |   3     4       1.000 |   3     4      -1.000 |
| | -     +       coef. |   n   | n       coef. |
|-----------------------|-----------------------|
|   0     1       1.000 |   0     0       5.000 |
|   1     2       1.000 |   1     1       5.000 |
|   2     3       1.000 |   2     2       5.000 |
|   3     4       1.000 |   3     3       5.000 |
|                       |   4     4       5.000 |



In [22]:
import quante as qt
op = qt.generate.operas.fermion

L = 5
builder = op.SpinfulFermionBuilder()
for i in range(L-1):
    builder += "+-|", [i, i+1], -1.0
    builder += "-+|", [i, i+1], 1.0
    builder += "|+-", [i, i+1], -1.0
    builder += "|-+", [i, i+1], 1.0
for i in range(L):
    builder += "n|n", [i, i], 5.0
ham = builder.build()
ham


SpinfulFermionOper (SpinUp | SpinDown) at 0x1a4eb3a17f0, 
|   +     -   |   coef. |   -     +   |   coef. | | +     -       coef. |
|-----------------------|-----------------------|-----------------------|
|   0     1      -1.000 |   0     1       1.000 |   0     1      -1.000 |
|   1     2      -1.000 |   1     2       1.000 |   1     2      -1.000 |
|   2     3      -1.000 |   2     3       1.000 |   2     3      -1.000 |
|   3     4      -1.000 |   3     4       1.000 |   3     4      -1.000 |
| | -     +       coef. |   n   | n       coef. |
|-----------------------|-----------------------|
|   0     1       1.000 |   0     0       5.000 |
|   1     2       1.000 |   1     1       5.000 |
|   2     3       1.000 |   2     2       5.000 |
|   3     4       1.000 |   3     3       5.000 |
|                       |   4     4       5.000 |

In [25]:
import quante as qt
op = qt.generate.operas.fermion

L = 5
builder = op.SpinfulFermionBuilder()
for i in range(L-1):
    builder += "+-|", [i, i+1], -1.0
    builder += "-+|", [i, i+1], 1.0
    builder += "|+-", [i, i+1], -1.0
    builder += "|-+", [i, i+1], 1.0
for i in range(L):
    builder += "n|n", [i, i], 5.0
ham = builder.build()

basis = qt.generate.basis.quspin_spinful_fermion_basis(L=L)
mat = ham.to_matrix(basis, dtype=np.float64)
mat

array([[25.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0., 20., -1., ...,  0.,  0.,  0.],
       [ 0., -1., 20., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0., -1.,  0.],
       [ 0.,  0.,  0., ..., -1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [27]:
# 展成 spinless fermion
import quante as qt
op = qt.generate.operas.fermion

L = 5
builder = op.SpinfulFermionBuilder()
for i in range(L-1):
    builder += "+-|", [i, i+1], -1.0
    builder += "-+|", [i, i+1], 1.0
    builder += "|+-", [i, i+1], -1.0
    builder += "|-+", [i, i+1], 1.0
for i in range(L):
    builder += "n|n", [i, i], 5.0
ham = builder.build()
ham = ham.to_spinless(mode='extend')
ham

FermionOper at 0x1a4ec917530, 
|   +     -       coef. |   -     +       coef. |   n     n       coef. |
|-----------------------|-----------------------|-----------------------|
|   0     1      -1.000 |   0     1       1.000 |   0     5       5.000 |
|   1     2      -1.000 |   1     2       1.000 |   1     6       5.000 |
|   2     3      -1.000 |   2     3       1.000 |   2     7       5.000 |
|   3     4      -1.000 |   3     4       1.000 |   3     8       5.000 |
|   5     6      -1.000 |   5     6       1.000 |   4     9       5.000 |
|   6     7      -1.000 |   6     7       1.000 |
|   7     8      -1.000 |   7     8       1.000 |
|   8     9      -1.000 |   8     9       1.000 |

In [31]:
# 展成 spinless fermion
import quante as qt
op = qt.generate.operas.fermion

L = 5
builder = op.SpinfulFermionBuilder()
for i in range(L-1):
    builder += "+-|", [i, i+1], -1.0
    builder += "-+|", [i, i+1], 1.0
    builder += "|+-", [i, i+1], -1.0
    builder += "|-+", [i, i+1], 1.0
for i in range(L):
    builder += "n|n", [i, i], 5.0
ham = builder.build()
ham = ham.to_spinless(mode='extend')

basis = qt.generate.basis.quspin_spinless_fermion_basis(L=2*L)
mat = ham.to_matrix(basis, dtype=np.float64)
mat, np.linalg.eigvalsh(mat)[0]

(array([[25.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0., 20., -1., ...,  0.,  0.,  0.],
        [ 0., -1., 20., ...,  0.,  0.,  0.],
        ...,
        [ 0.,  0.,  0., ...,  0., -1.,  0.],
        [ 0.,  0.,  0., ..., -1.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]]),
 np.float64(-3.382617960996765))

In [32]:
# 展成 spinless fermion
import quante as qt
op = qt.generate.operas.fermion

L = 5
builder = op.SpinfulFermionBuilder()
for i in range(L-1):
    builder += "+-|", [i, i+1], -1.0
    builder += "-+|", [i, i+1], 1.0
    builder += "|+-", [i, i+1], -1.0
    builder += "|-+", [i, i+1], 1.0
for i in range(L):
    builder += "n|n", [i, i], 5.0
ham = builder.build()
ham = ham.to_spinless(mode='near')

basis = qt.generate.basis.quspin_spinless_fermion_basis(L=2*L)
mat = ham.to_matrix(basis, dtype=np.float64)
mat, np.linalg.eigvalsh(mat)[0]

(array([[25.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0., 20.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0., 20., ...,  0.,  0.,  0.],
        ...,
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]]),
 np.float64(-3.382617960996697))